version: '3.9'
services:
  postgres:
      image: postgres:15
      environment:
        POSTGRES_DB: video_m8
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: mysecretpassword
      ports:
          - "5432:5432"
  web:
    build: ..
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres