# Generated by Django 4.1.5 on 2023-01-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='miniature',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
